- App.js
- package-lock.json
- package.json
- src/screens/LoginScreen.js
- src/screens/SignUpScreen.js
**개요**
- feat: stack navigator, screen 추가
**타입**
**작업 사항**
- react-navigation 라이브러리 추가했습니다.
- stack-navigator 추가했습니다.
- 로그인 스크린과 회원가입 스크린을 구현했습니다.
- 로그인 스크린에서 회원가입 스크린으로 성공적으로 이동되는 것을 확인했습니다.
**Test**🧪
> feat: stack navigator, screen 추가

- App.js
- package-lock.json
- package.json
- src/components/Typography.js
- src/navigators/RootNavigator.js
- src/navigators/TabNavigator.js
- src/screens/HomeScreen.js
- src/screens/LoginScreen.js
- src/screens/MyPageScreen.js
> feat: Navigator 생성 및 폴더 구조 설정

- src/components/Header.js
- src/components/Margin.js
- src/components/MoveButton.js
- src/components/SelectButton.js
- src/screens/SignUp/SignUpScreenFirst.js
- src/screens/SignUp/SignUpScreenFourth.js
- src/screens/SignUp/SignUpScreenSecond.js
- src/screens/SignUp/SignUpScreenThird.js
**개요**
- feat: 회원가입 가입 유형 선택 화면 구현
**타입**
**작업 사항**
- 회원가입 버튼을 눌렀을 때 나타나는 가입 유형 선택 화면을 구현하고 있습니다.
**Test**🧪
> feat: 회원가입 가입 유형 선택 화면 구현

- package-lock.json
- package.json
- src/components/SignUpForm/SignUpBasic.js
- src/components/SignUpTitle.js
- src/screens/SignUp/SignUpScreenFirst.js
- src/screens/SignUp/SignUpScreenSecond.js
**개요**
- feat: 회원가입 - 로그인 정보 기입 화면 구현
**타입**
**작업 사항**
- 회원가입 화면 첫 번째 스크린 - 로그인 정보 기입하기를 구현 중에 있습니다.
- Formik과 Yup 라이브러리를 활용하여, 폼 상태 관리를 진행했습니다.
**Test**🧪
> feat: 회원가입 - 로그인 정보 기입 화면 구현

- src/screens/SignUp/SignUpScreenFourth.js
- src/screens/SignUp/SignUpScreenSecond.js
- src/screens/SignUp/SignUpScreenThird.js
**개요**
- feat: 회원가입 각 스크린 이동 버튼 및 제목 추가
**타입**
**작업 사항**
- 회원가입 각 스크린에 이동 버튼 및 제목을 추가했습니다.
**Test**🧪
> feat: 회원가입 각 스크린 이동 버튼 및 제목 추가

- package-lock.json
- package.json
- src/components/SignUpForm/SignUpAgreement.js
- src/screens/SignUp/SignUpScreenFourth.js
**개요**
- feat: BouncyCheckBox 라이브러리 추가 및 동의 버튼 구현
**타입**
**작업 사항**
- 체크 박스 라이브러리를 추가하고 약관 동의 스크린에 체크 버튼을 구현하고 있습니다.
**Test**🧪
> feat: BouncyCheckBox 라이브러리 추가 및 동의 버튼 구현

- src/components/SignUpForm/SignUpAgreement.js
- src/screens/SignUp/SignUpScreenFourth.js
**개요**
- feat: 약관 동의 스크린 구현
**타입**
**작업 사항**
- 약관 동의 스크린 구현 중에 있습니다.
**Test**🧪
> feat: 약관 동의 스크린 구현

- App.js
- package-lock.json
- package.json
- src/actions/selectRole.js
- src/components/SelectButton.js
- src/navigators/SignUpNavigator.js
- src/reducers/role.js
- src/screens/SignUp/SignUpScreenFifth.js
- src/screens/SignUp/SignUpScreenFirst.js
- src/screens/SignUp/SignUpScreenFourth.js
- src/screens/SignUp/SignUpScreenSecond.js
- src/store/store.js
**개요**
- feat: redux 라이브러리 설치 및 전역 상태 관리 구현
**타입**
**작업 사항**
- redux, react-redux 라이브러리를 설치했습니다.
- 가입할 때, tutor 혹은 tutee의 가입 유형을 전역 상태로 저장하여 관리하고자 합니다.
- 해당 값이 그 다음 스크린에서 성공적으로 불러와지는 것을 확인했습니다.
**Test**🧪
> feat: redux 라이브러리 설치 및 전역 상태 관리 구현

- src/components/MoveButton.js
- src/components/SignUpForm/SignUpAgreement.js
- src/screens/SignUp/SignUpScreenAgreement.js
**개요**
- feat: 필수 약관 동의 시 화면 전환 기능 구현
**타입**
**작업 사항**
- 필수 약관 동의 했을 때, 스크린이 전환 가능할 수 있도록 기능을 구현했습니다.
**Test**🧪
> feat: 필수 약관 동의 시 화면 전환 기능 구현

- src/components/MoveButton.js
- src/components/SignUpForm/SignUpBasic.js
- src/screens/SignUp/SignUpScreenAgreement.js
- src/screens/SignUp/SignUpScreenComplete.js
- src/screens/SignUp/SignUpScreenFillInfo.js
- src/screens/SignUp/SignUpScreenSelect.js
**개요**
- fix: Formik values 외부에서 접근할 수 있도록 수정
**타입**
**작업 사항**
- 스크린과 컴포넌트 설계 구조 상 Formik values를 Formik 외부에서 받아야 할 필요가 있었습니다. 따라서 useRef()를 통해, 해당 값을 외부 컴포넌트로 전달할 수 있게 구현했습니다.
- 전환 버튼의 글자를 수정할 수 있도록 삼항 조건 연산자 대신, text를 따로 설정하여, 버튼의 이름을 바꿀 수 있도록 했습니다. 
**Test**🧪
> fix: Formik values 외부에서 접근할 수 있도록 수정

- package-lock.json
- package.json
- src/components/Schedule/Calendar.js
- src/components/Schedule/CalendarHeader.js
- src/components/Schedule/CurrentDate.js
- src/components/Schedule/TimePickerModal.js
- src/hooks/useCalendar.js
**개요**
- feat: 날짜 선택 모달 구현
**타입**
**작업 사항**
- react native date picker modal 라이브러리를 활용하여, 날짜 선택 모달을 구현했습니다.
**Test**🧪
> feat: 날짜 선택 모달 구현

- package-lock.json
- package.json
- src/navigators/RootNavigator.js
- src/screens/ScheduleScreen.js
**개요**
- schdule -> schedule 오타 수정
- ScheduleScreen 에 Calendar component 가 import 되어 있던데 디렉토리 파일에는 없는 듯해서 일단 삭제함
**타입**
**작업 사항**
- 작업 사항 자세하게 적어주세요.
**Test**🧪
> Chore: Schedule 오타 수정

- package-lock.json
- package.json
- src/apis/Class.js
- src/apis/Token.js
- src/apis/User.js
**개요**
- feat: Axios 라이브러리 설치 및 API 모듈 분리
**타입**
**작업 사항**
- 백 엔드 서버와의 통신을 위한 Axios 라이브러리를 설치했습니다.
- API 모듈 분리화 관리를 위한 API 폴더를 따로 생성했습니다.
- user 부분과 class 부분에 완성된 API를 입력했습니다. IF-02 ~ IF-09
**Test**🧪
> feat: Axios 라이브러리 설치 및 API 모듈 분리

- src/navigators/RootNavigator.js
- src/navigators/TabNavigator.js
- src/screens/ClassroomScreen.js
**개요**
- ScheduleScreen 을 ClassroomScreen 으로 명칭 변경
**타입**
**작업 사항**
- 명칭 변경 사유: 학생관리 화면에 스케줄 기능만 있는 것이 아님. 
- 
**Test**🧪
> Chore: ScheduleScreen -> ClassroomScreen

- src/navigators/RootNavigator.js
- src/navigators/SignUpNavigator.js
- src/navigators/TabNavigator.js
- src/screens/ClassroomScreen.js
**개요**
- feat: 네비게이션 스크린 전환 애니메이션 변경
**타입**
**작업 사항**
- 회원가입 스크린 전환 애니메이션을 변경했습니다.
**Test**🧪
> feat: 네비게이션 스크린 전환 애니메이션 변경

- src/components/Calendar/Calendar.js
- src/components/Classroom/AssignmentButton.js
- src/components/Classroom/AssignmentPreview.js
- src/components/Classroom/ReviewButton.js
- src/components/Classroom/ReviewPreview.js
- src/components/Header.js
- src/navigators/RootNavigator.js
- src/screens/ClassroomScreen.js
**개요**
- feat: 클래스룸 스크린 UI 구현
**타입**
**작업 사항**
- 일정 관리 스크린 UI 구현 중에 있습니다.
- 현재 숙제 관리 및 복습 관리 UI를 정보를 볼 수만 있고, 해당 스크린으로 넘어가는 버튼으로 구현하고 있습니다.
**Test**🧪
- 진도율 부분과 관련된 로직을 어떻게 적용할 지 조금 더 논의해보겠습니다.
- 정보를 넣게 된다면 해당 정보에 맞는 아이템을 FlatList로 render하는 방향으로 리팩토링 진행하겠습니다.
- RN에서는 borderBottom이나 borderTop을 독자적으로 제공하지 않는다는 것을 알게 되었습니다.
- 대신 FlatList의 Seperator를 사용할 계획입니다.
> feat: 클래스룸 스크린 UI 구현

- src/components/Calendar/Calendar.js
- src/components/Calendar/CalendarHeader/CalendarHeader.js
- src/components/Classroom/AssignmentButton.js
- src/components/Classroom/ReviewButton.js
**개요**
- chore: 달력 컴포넌트 크기 수정
**타입**
**작업 사항**
- 달력 컴포넌트 폰트 크기를 12px에서 14px로 전반적으로 키웠습니다.
**Test**🧪
> chore: 달력 컴포넌트 크기 수정

- src/components/TabBar.js
- src/navigators/RootNavigator.js
- src/screens/ClassroomScreen.js
- src/screens/HomeScreen.js
**개요**
- 간단한 개요 정리
**타입**
**작업 사항**
- ui 만 있음
**Test**🧪
> Feat: TabBar

- package-lock.json
- src/navigators/RootNavigator.js
- src/screens/LoginScreen.js
**개요**
- 회원가입 버튼 스타일 수정
**타입**
**작업 사항**
- Button 말고 TouchableOpacity 사용
**Test**🧪
> Style: 회원가입 버튼 스타일 수정

- src/components/buttons/LoginBtn.js
- src/screens/LoginScreen.js
**개요**
- 로그인 TouchableOpacity  및 navigation
**타입**
**작업 사항**
- 작업 사항 자세하게 적어주세요.
**Test**🧪
> Fix: 로그인 TouchableOpacity 적용

- src/components/Home/StudentList.js
**개요**
- 학생 목록 스타일링
**타입**
**작업 사항**
- width, height 제거 및 padding 추가
**Test**🧪
> Style: 학생 목록 스타일링

- src/navigators/ClassroomNavigator.js
- src/navigators/RootNavigator.js
- src/navigators/TabNavigator.js
**개요**
- style: 네비게이터 구성 수정
**타입**
**작업 사항**
- 클래스룸 스크린이 또 하나의 네비게이터로 구성되어야 한다는 것을 인지하고, 스택 네비게이터로 감싸줬습니다.
**Test**🧪
> style: 네비게이터 구성 수정

- src/components/Header.js
- src/components/Home/StudentData.js
- src/navigators/TabNavigator.js
**개요**
- 탭바 UI
**타입**
**작업 사항**
- 헤더 사라짐
**Test**🧪
> Feat: 탭바 UI

- src/components/Classroom/ReviewButton.js
- src/components/Header.js
- src/navigators/ClassroomNavigator.js
- src/navigators/ReviewNavigator.js
- src/screens/ClassroomScreen.js
- src/screens/ReviewScreen.js
**개요**
- chore: 오탈자 수정
**타입**
**작업 사항**
- 오탈자 수정
**Test**🧪
> chore: 오탈자 수정

- src/components/Review/AddReview.js
- src/components/Review/AddReviewButton.js
- src/components/Review/CheckButton.js
- src/components/Review/ReviewListContainer.js
- src/navigators/ReviewNavigator.js
- src/screens/AddReviewScreen.js
- src/screens/ReviewScreen.js
**개요**
- feat: 복습 노트 체크 박스 추가
**타입**
**작업 사항**
- 복습 노트 체크 박스 추가
**Test**🧪
> feat: 복습 노트 체크 박스 추가

- App.js
- src/components/Header.js
- src/components/Review/AddReviewButton.js
- src/global/theme/theme.js
- src/navigators/TabNavigator.js
- src/screens/ReviewScreen.js
**개요**
- style: ThemeProvider 및 Font 등 서식 정리
**타입**
**작업 사항**
- styled-components/native의 ThemeProvider를 추가하여, 자주 쓰는 색상을 테마에 저장하여 관리할 수 있게 했습니다.
- 폰트의 글꼴을 모두 추가하였고, 각각 굵기에 따라 구분할 수 있게 했습니다.
- 현재 회원가입 완료 스크린과 복습 노트 추가 스크린을 구현하고 있습니다.
**Test**🧪
> style: ThemeProvider 및 Font 등 서식 정리

- src/components/Review/AddReview.js
- src/components/Review/AddReviewButton.js
- src/components/SignUp/MoveButton.js
- src/components/SignUp/SignUpButton.js
- src/components/SignUp/SignUpComplete.js
- src/global/theme/theme.js
- src/screens/LoginScreen.js
- src/screens/SignUp/SignUpScreenComplete.js
- src/screens/SignUp/SignUpScreenFillInfo.js
**개요**
- feat: SignUpComplete Screen UI 구현
**타입**
**작업 사항**
- SignUpComplete Screen UI 구현 중에 있습니다.
**Test**🧪
> feat: SignUpComplete Screen UI 구현

- src/components/Classroom/AssignmentNoteBtn.js
- src/screens/ClassroomScreen.js
**개요**
-복습노트 UI 개발 중
**타입**
**작업 사항**
- navigation 완료
- 아이콘 추가 예정
**Test**🧪
> Feat: 복습노트 UI 개발 중
